version: '2'
services:
    food-mongodb:
        container_name: food-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/food/mongodb/:/data/db/
